### ISSUE TITLE
Guzzle requirement missing from composer.json

### ISSUE THREAD

**Issue by clarkwinkelmann** [NomisCZ/flarum-ext-auth-steam#12]
This extension uses `guzzlehttp/guzzle` but does not explicitly requires it in `composer.json`. This will cause errors if users have no other extensions that require `guzzlehttp/guzzle`.

**Comment by NomisCZ** [comment]
Hello,
thanks for the info. I'll check it.

**Comment by NomisCZ** [comment]
Guzzle is required by Laravel, so is not necessary to explicitly require it.

**Comment by clarkwinkelmann** [comment]
Actually, it isn't.

Flarum does not require the `laravel/framework` or `laravel/laravel` package directly, but instead directly requires some of the individual Laravel packages, none of them require Guzzle.

Laravel only added Guzzle as a requirement to `laravel/laravel` in a later version, but this has no influence on Flarum because we don't use the Laravel scaffolding.

`composer why guzzlehttp/guzzle` will show you which other dependencies actually require Guzzle on your forum. No Laravel packages are in there.

You can reproduce the issue by removing all other social login extensions and Upload with Composer. You'll see Guzzle is no longer installed.

Even if one of your dependencies had Guzzle as a dependency (which is not the case here), it's best practice to explicitly require it yourself as that dependency could drop Guzzle.

My report follows the findings discussed at https://discuss.flarum.org/d/23034-flarum-query-extensions-big-data-analysis/2
