### ISSUE TITLE
No confirmation email being sent when users logs in with steam

### ISSUE THREAD

**Issue by ChrisF999** [NomisCZ/flarum-ext-auth-steam#14]

**Comment by NomisCZ** [comment]
Hi,
I tested it.

Forum message:
![image](https://user-images.githubusercontent.com/7500606/79499727-b2352d80-802b-11ea-95e3-946d4a1281d0.png)

Email:
![image](https://user-images.githubusercontent.com/7500606/79499937-fb857d00-802b-11ea-8064-db7a23c5f0d9.png)

Looks like you're having trouble with your mail config.
Don't hesitate to ask on the official forum https://discuss.flarum.org.
