### ISSUE TITLE
Can you tell me how to add language

### ISSUE THREAD

**Issue by Nekoer** [NomisCZ/flarum-ext-auth-steam#2]
Such as Chinese

**Comment by NomisCZ** [comment]
Hello,
you need to create <lang>.yml in /resources/locale. 
Template: https://github.com/NomisCZ/flarum-ext-auth-steam/blob/master/resources/locale/en.yml

If you want to, you can create translation, then create merge request and I can push it into my package.

**Comment by NomisCZ** [comment]
MR: #3
