### ISSUE TITLE
Both the admin page and the login page cannot display the translation correctly

### ISSUE THREAD

**Issue by LCinHK** [NomisCZ/flarum-ext-auth-steam#4]
![1](https://user-images.githubusercontent.com/49670244/69937030-7bdf9180-1514-11ea-92c4-f20ab40bf95a.png)
![2](https://user-images.githubusercontent.com/49670244/69937053-99146000-1514-11ea-95e3-22dfa8ecf749.png)

**Comment by NomisCZ** [comment]
Hello,
it looks like problem with resources/locale/cn.yml, it should be zh.yml. I'll rename it ASAP.

Temporary you can rename this file in vendor/nomiscz/flarum-ext-auth-steam/resources/locale/cn.yml to zh.yml.

**Comment by LCinHK** [comment]
> cn.yml to zh.yml

It seems that your solution is for [This one](https://github.com/Flarum-Chinese/flarum-ext-simplified-chinese), while the one I use was [this](https://github.com/Csineneo/lang-simplified-chinese)

Any way, thanks for your help!!! I changed "cn.yml" to "zh-hans.yml" and the problem solved..
