### ISSUE TITLE
Steam OpenID API URL steamcommunity.com is not available in China

### ISSUE THREAD

**Issue by NomisCZ** [NomisCZ/flarum-ext-auth-steam#7]
Change all "steamcommunity.com" into "steampowered.com", because the domain "steamcommunity.com" is blocked in China, while "steampowered.com" is not.

Thanks @LCinHK
Pull request: #6 - closed, because it needs a better implementation

**Comment by BoneTM** [comment]
now the `steampowered.com` actually wont work anymore
`steampowered.com` is only for oauth2 now
`steamcommunity.com` is for openid

**Comment by NomisCZ** [comment]
> now the `steampowered.com` actually wont work anymore
> `steampowered.com` is only for oauth2 now
> `steamcommunity.com` is for openid

Valve changed that (availability of steamcommunity behind the Great Firewall of China), but OAuth2 is only available for partner sites/apps on embedded platforms. Non-partners can use OpenID with the Steam Web API key.

https://partner.steamgames.com/doc/webapi_overview/oauth
https://partner.steamgames.com/doc/features/auth#website
